### ISSUE TITLE
Publish fails with v2.5.1

### ISSUE THREAD

**Issue by bpandola** [sphinx-contrib/confluencebuilder#966]
```# Platform:         darwin; (macOS-13.6-x86_64-i386-64bit)
# Sphinx version:   7.3.7
# Python version:   3.9.18 (CPython)
# Docutils version: 0.21.2
# Jinja2 version:   3.1.4
# Pygments version: 2.18.0

# Last messages:
#   done
#
#   writing output... [100%]
#   index
#
#
#
#   publishing documents... [100%]
#   index
#

# Loaded extensions:
#   sphinx.ext.mathjax (7.3.7)
#   alabaster (0.7.16)
#   sphinxcontrib.applehelp (1.0.8)
#   sphinxcontrib.devhelp (1.0.6)
#   sphinxcontrib.htmlhelp (2.0.5)
#   sphinxcontrib.serializinghtml (1.1.10)
#   sphinxcontrib.qthelp (1.0.7)
#   sphinxcontrib.confluencebuilder (2.5.1)

# Traceback:
Traceback (most recent call last):
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinx/cmd/build.py", line 337, in build_main
    app.build(args.force_all, args.filenames)
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_all()
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 252, in build_all
    self.build(None, summary=__('all source files'), method='all')
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 365, in build
    self.finish()
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 760, in finish
    self.publish_doc(docname, output)
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinxcontrib/confluencebuilder/builder.py", line 500, in publish_doc
    uploaded_id = self.publisher.store_page_by_id(title,
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 1171, in store_page_by_id
    self._update_page(page, page_name, data)
  File "/Users/bpandola/PyCharmProjects/rds-service-broker/env/py3.9/lib/python3.9/site-packages/sphinxcontrib/confluencebuilder/publisher.py", line 1545, in _update_page
    orig_meta_props = orig_metadata.setdefault('properties', {})
AttributeError: 'NoneType' object has no attribute 'setdefault'
```

https://github.com/sphinx-contrib/confluencebuilder/blob/d4151d3dbfd10e6e8e5c6f9e24b567e44c6c1c49/sphinxcontrib/confluencebuilder/publisher.py#L1521

If I change the `None` in the above line to `{}`, the publish succeeds; but I'm not sure if that property should be there and its absence is due to some other failure happening further up the call stack.

**Comment by jdknight** [comment]
@bpandola, thanks for the report. For sure looks like an implementation error (both 1521 and 1522). The proposed change (switching `None` to `{}`) seems like a correct approach.

A workaround would be to force using the v1 API (or the interim change suggested):

```
confluence_api_mode = 'v1'
```

**Comment by jdknight** [comment]
A fix has been applied to #967 and a v2.5.2 release has been made with the fix. Will proceed to close this issue.

Please feel free to report any other issues you may encounter. Thanks again.

**Comment by bpandola** [comment]
@jdknight Just wanted to say Thanks! for the workaround and the quick patch.  I appreciate it!
